{{- if .Values.ingress.enabled }}
{{- if not .Values.ingress.host }}
{{- fail "ingress.host ist nötig, wenn ingress.enabled=true" }}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kickertool.fullname" . }}
  labels:
    {{- include "kickertool.labels" (dict "ctx" . "component" "app") | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "kickertool.fullname" . }}
                port:
                  name: http
    {{- if and .Values.keycloak.enabled .Values.ingress.keycloakHost }}
    - host: {{ .Values.ingress.keycloakHost | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "kickertool.keycloakName" . }}
                port:
                  name: http
    {{- end }}
{{- end }}
